### ISSUE TITLE
[BUG]: [charts/karavi-metrics-powerflex]: Use yaml multiline for ConfigMap files

### ISSUE THREAD

**Issue by coulof** [dell/helm-charts#70]
**Describe the bug**
The current version put config files as quoted-string which makes it difficult to modify in Kubernetes manually since indentation is part of the language. It will be better to use yaml mutltiline

**Comment by ioeicicdsvc** [comment]
@coulof: Thank you for submitting this issue!

The issue is currently awaiting triage. Please make sure you have given us as much context as possible.

If the maintainers determine this is a relevant issue, they will remove the needs-triage label and assign an appropriate priority label.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at karavi@dell.com.

**Comment by coulof** [comment]
Done in PR #71
